version: '3.3'

services:
  app:
    container_name: nearby-django
    build:
      context: ./docker/django
    ports:
      - 8000:8000
    volumes:
      - ./SOP:/app
    command: bash -c "python manage.py migrate && nohup python manage.py runserver 0.0.0.0:8000"

  tasks:
    build:
      context: ./docker/django
    volumes:
      - ./SOP:/app
    command: python3 manage.py process_tasks
    depends_on:
      - app
