-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 10:27:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nearby
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nearby
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nearby` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `nearby` ;

-- -----------------------------------------------------
-- Table `nearby`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearby`.`Place` (
  `idPlace` INT NOT NULL AUTO_INCREMENT,
  `place_name` VARCHAR(255) NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  PRIMARY KEY (`idPlace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nearby`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearby`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `IP` VARCHAR(255) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `IP_UNIQUE` (`IP` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nearby`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearby`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(255) NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nearby`.`Tag_Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearby`.`Tag_Place` (
  `Tag_idTag` INT NOT NULL,
  `Place_idPlace` INT NOT NULL,
  PRIMARY KEY (`Tag_idTag`, `Place_idPlace`),
  INDEX `fk_Tag_has_Place_Place1_idx` (`Place_idPlace` ASC) VISIBLE,
  INDEX `fk_Tag_has_Place_Tag_idx` (`Tag_idTag` ASC) VISIBLE,
  CONSTRAINT `fk_Tag_Place_Tag`
    FOREIGN KEY (`Tag_idTag`)
    REFERENCES `nearby`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_Place_Place1`
    FOREIGN KEY (`Place_idPlace`)
    REFERENCES `nearby`.`Place` (`idPlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nearby`.`Place_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nearby`.`Place_User` (
  `Place_idPlace` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `avg_spending_time` FLOAT NULL,
  `visit_count` INT NULL,
  `ranking` INT NULL,
  PRIMARY KEY (`Place_idPlace`, `User_idUser`),
  INDEX `fk_Place_has_User_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Place_has_User_Place1_idx` (`Place_idPlace` ASC) VISIBLE,
  CONSTRAINT `fk_Place_User_Place1`
    FOREIGN KEY (`Place_idPlace`)
    REFERENCES `nearby`.`Place` (`idPlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Place_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `nearby`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
