# Generated by Django 2.2 on 2019-11-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('idplace', models.AutoField(db_column='idPlace', primary_key=True, serialize=False)),
                ('place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Place',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('idtag', models.AutoField(db_column='idTag', primary_key=True, serialize=False)),
                ('tag_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='PlaceUser',
            fields=[
                ('placeuser_id', models.AutoField(db_column='placeuser_id', primary_key=True, serialize=False)),
                ('avg_spending_time', models.FloatField(blank=True, null=True)),
                ('visit_count', models.IntegerField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('place_idplace', models.ForeignKey(db_column='Place_idPlace', on_delete=django.db.models.deletion.DO_NOTHING, to='nearby.Place')),
                ('user_iduser', models.ForeignKey(db_column='User_idUser', on_delete=django.db.models.deletion.DO_NOTHING, to='nearby.User')),
            ],
            options={
                'db_table': 'Place_User',
                'unique_together': {('place_idplace', 'user_iduser')},
            },
        ),
        migrations.CreateModel(
            name='TagPlace',
            fields=[
                ('tag_idtag', models.ForeignKey(db_column='Tag_idTag', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nearby.Tag')),
                ('place_idplace', models.ForeignKey(db_column='Place_idPlace', on_delete=django.db.models.deletion.DO_NOTHING, to='nearby.Place')),
            ],
            options={
                'db_table': 'Tag_place',
                'unique_together': {('tag_idtag', 'place_idplace')},
            },
        ),
    ]
