# Generated by Django 2.2.7 on 2019-11-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('idplace', models.AutoField(db_column='idPlace', primary_key=True, serialize=False)),
                ('place_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('idtag', models.AutoField(db_column='idTag', primary_key=True, serialize=False)),
                ('tag_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceUser',
            fields=[
                ('place_idplace', models.ForeignKey(db_column='Place_idPlace', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nearby.Place')),
                ('avg_spending_time', models.FloatField(blank=True, null=True)),
                ('visit_count', models.IntegerField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'place_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagPlace',
            fields=[
                ('tag_idtag', models.ForeignKey(db_column='Tag_idTag', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='nearby.Tag')),
            ],
            options={
                'db_table': 'tag_place',
                'managed': False,
            },
        ),
    ]
