# Generated by Django 2.2 on 2019-11-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
