server:
  port: 9090
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  routes:
    studentservice: '/student/**'
    DJANGO-TEST-API: '/test_api/**'